
name: TestCafe Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run TestCafe tests
      run: npx testcafe chrome:headless src/test/testCreate.js && npx testcafe chrome:headless src/test/testNavegacion.js

